export function questsForGrade(grade) {
  const sets = {
    S: [
      {
        name: 'Wrist Circles',
        nameKo: '손목 돌리기',
        sets: '2 sets',
        reps: '10 reps each direction',
        illustration: 'Open hand, draw slow circles in both directions',
        xp: 30,
        icon: '🔄',
      },
      {
        name: 'Finger Fan Stretch',
        nameKo: '손가락 펼치기',
        sets: '2 sets',
        reps: 'Hold 15s × 4',
        illustration: 'Spread fingers wide, then make a fist',
        xp: 25,
        icon: '🖐️',
      },
      {
        name: 'Prayer Stretch',
        nameKo: '합장 스트레칭',
        sets: '1 set',
        reps: 'Hold 30s × 3',
        illustration: 'Press palms together, lower until you feel a gentle pull',
        xp: 35,
        icon: '🙏',
      },
    ],
    A: [
      {
        name: 'Wrist Circles',
        nameKo: '손목 돌리기',
        sets: '2 sets',
        reps: '10 reps each direction',
        illustration: 'Slow controlled circles, both hands',
        xp: 30,
        icon: '🔄',
      },
      {
        name: 'Prayer Stretch',
        nameKo: '합장 스트레칭',
        sets: '2 sets',
        reps: 'Hold 30s × 3',
        illustration: 'Press palms together, lower the wrists slowly',
        xp: 35,
        icon: '🙏',
      },
      {
        name: 'Tendon Glides',
        nameKo: '힘줄 활주 운동',
        sets: '2 sets',
        reps: '8 reps',
        illustration: 'Move fingers through five hand positions slowly',
        xp: 40,
        icon: '✋',
      },
    ],
    B: [
      {
        name: 'Wrist Flexor Stretch',
        nameKo: '손목 굴곡근 스트레칭',
        sets: '3 sets',
        reps: 'Hold 30s each side',
        illustration: 'Arm out, palm up, pull fingers down with the other hand',
        xp: 40,
        icon: '⬇️',
      },
      {
        name: 'Wrist Extensor Stretch',
        nameKo: '손목 신전근 스트레칭',
        sets: '3 sets',
        reps: 'Hold 30s each side',
        illustration: 'Arm out, palm down, gently pull the back of the hand',
        xp: 40,
        icon: '⬆️',
      },
      {
        name: 'Resistance Band Curls',
        nameKo: '저항 밴드 컬',
        sets: '3 sets',
        reps: '12 reps each direction',
        illustration: 'Anchor band, curl wrist up and down slowly',
        xp: 55,
        icon: '🎯',
      },
      {
        name: 'Grip Squeezes',
        nameKo: '쥐기 운동',
        sets: '3 sets',
        reps: '15 squeezes',
        illustration: 'Squeeze a soft ball or towel, hold 2 seconds',
        xp: 45,
        icon: '🥎',
      },
      {
        name: 'Forearm Pronation/Supination',
        nameKo: '전완 회전 운동',
        sets: '2 sets',
        reps: '12 reps each side',
        illustration: 'Hold a light weight, rotate the palm up and down',
        xp: 50,
        icon: '🔁',
      },
    ],
    C: [
      {
        name: 'Wrist Rest Pose',
        nameKo: '손목 휴식 자세',
        sets: '4 sets',
        reps: 'Hold 1 min',
        illustration: 'Lay forearm flat on a table, palm up, fully relaxed',
        xp: 25,
        icon: '🛌',
      },
      {
        name: 'Ice Pack Therapy',
        nameKo: '냉찜질',
        sets: '1 round',
        reps: '10 min × 3 / day',
        illustration: 'Wrap an ice pack in a thin cloth and rest it on the wrist',
        xp: 30,
        icon: '🧊',
      },
      {
        name: 'Gentle Wrist Glides',
        nameKo: '부드러운 손목 움직임',
        sets: '2 sets',
        reps: '8 reps slow',
        illustration: 'Tiny pain-free flexion/extension only',
        xp: 35,
        icon: '🌊',
      },
      {
        name: 'Thumb Opposition',
        nameKo: '엄지 맞닿기',
        sets: '2 sets',
        reps: 'Touch each fingertip 5 times',
        illustration: 'Lightly touch the thumb to each fingertip',
        xp: 30,
        icon: '👌',
      },
      {
        name: 'Warm Compress',
        nameKo: '온찜질',
        sets: '1 round',
        reps: '10 min once daily',
        illustration: 'Use a warm towel before stretching to relax tissue',
        xp: 35,
        icon: '🔥',
      },
      {
        name: 'Massage Roll',
        nameKo: '전완 마사지',
        sets: '2 sets',
        reps: '2 min each forearm',
        illustration: 'Gently knead the forearm muscles toward the elbow',
        xp: 40,
        icon: '💆',
      },
      {
        name: 'Specialist Consultation',
        nameKo: '전문의 상담 예약',
        sets: '1 quest',
        reps: 'Schedule within 7 days',
        illustration: 'Book a visit with an orthopedic or hand specialist',
        xp: 80,
        icon: '🏥',
      },
    ],
  };
  return sets[grade] ?? sets.A;
}
